create table if not exists public.waitlist_signups (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text,
  campaign text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint waitlist_email_length check (char_length(email) between 3 and 254)
);

alter table public.waitlist_signups enable row level security;

comment on table public.waitlist_signups is
  'Server-only UES-owned BlindBoxAI waitlist storage. Contains email PII; no client policies are granted.';
